### ISSUE TITLE
should replace `ml_hal_fit` with `squashed` right?

### ISSUE THREAD

**Issue by wilsoncai1992** [tlverse/hal9001#28]
https://github.com/jeremyrcoyle/hal9001/blob/9ab56bb964dbeda31641bc4b0c5380cad3613434/tests/testthat/test-hal.R#L48-L54

**Comment by nhejazi** [comment]
Thanks for pointing this out. Yes, it appears that `ml_hal_fit` should be replaced by `squashed` in lines 48 and 54.

**Comment by nhejazi** [comment]
Fixed at some point in the past.
