### ISSUE TITLE
Conflict with data.table package

### ISSUE THREAD

**Issue by rfherrerac** [tlverse/hal9001#42]
When I tried to install hal9001 this error came up
clang: error: unsupported option '-fopenmp'
make: *** [assign.o] Error 1
ERROR: compilation failed for package ‘data.table’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/data.table’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/data.table’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/var/folders/ph/l_06hx0d75x66h6f7dr3s72w0000gn/T//RtmpOicTJA/file5eb3aa883a7/data.table_1.12.3.tar.gz’ had non-zero exit status

R version 3.5.3 (2019-03-11) -- "Great Truth"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin15.6.0 (64-bit)

**Comment by jeremyrcoyle** [comment]
That error indicates that you have failed to build `data.table` package from source. This is an issue with your build environment. See https://thecoatlessprofessor.com/programming/openmp-in-r-on-os-x/ for instructions on how to resolve it.
