### ISSUE TITLE
predict method not working when  reduce_basis

### ISSUE THREAD

**Issue by sgruber65** [tlverse/hal9001#46]
Getting predictions from a hal fit that uses the "reduce_basis" argument fails. The error message is: `"Error in .local(x, y, ...) : 
  Cholmod error 'X and/or Y have wrong dimensions' at file ../MatrixOps/cholmod_sdmult.c, line 90".`
Here is a reproducible example:
```r
set.seed(385971)
n = 100
p = 3
x <- xmat <- matrix(rbinom(n * p, 1, .3), n, p)
y <- x[, 1] * sin(x[, 2]) + rnorm(n, mean = 0, sd = 0.2)

\# fit the HAL regression two ways
hal_fit1 <- fit_hal(X = x, Y = y)
pred1 <- predict(hal_fit1, new_data = x)  # this works
pct <- 10^-12
hal_fit2 <- fit_hal(X = x, Y = y, reduce_basis = pct)
pred2 <- predict(hal_fit2, new_data = x)  # this fails for many values of pct, e.g. .1, .2
```

**Comment by nhejazi** [comment]
Thank you for bringing this bug to our attention. A simple fix has been implemented in #47, which will soon be merged into branch `master`. We appreciate your patience in the delay in getting back to you and fixing this issue.
