### ISSUE TITLE
fitting grouped binomial

### ISSUE THREAD

**Issue by HughSt** [tlverse/hal9001#49]
Hi - just fitting a grouped binomial which works great by setting Y to be a 2 columned matrix of negatives and positives. To align with other model fitting functions (GLM, GAM etc.) you might want to stick to the convention of positives and negatives, i.e. columns the other way around. 

Thanks for the package!

**Comment by jeremyrcoyle** [comment]
Thanks Hugh. Our package relies on `glmnet` for the lasso fitting step, and outcomes are passed unprocessed directly to `glmnet`. To the extent that `glmnet` does things differently than other learners, that's unfortunate, but it's important to us that our package behaves like the underlying implementation at the lasso step

**Comment by HughSt** [comment]
Makes sense! Thanks
