### ISSUE TITLE
Issues installing the package

### ISSUE THREAD

**Issue by Bahamyirou** [tlverse/hal9001#54]
Hi,
Am trying to install the package and am having trouble to do it. Any help ?
Asma

**Comment by jeremyrcoyle** [comment]
You need to provide details, including what OS and R version you're on, what command you tried to run to install the package, and what error message you got. Without that, it will be impossible to help.

**Comment by Bahamyirou** [comment]
I am installing the packaes on Windows 10. R-3.6.1 I install the 3.6.2 version of R and retry it with the code :

with_libpaths(new = "C:/R-3.6.2/library",install_github("tlverse/hal9001", build_vignettes = FALSE))

And I got this error message: 


** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package 'Rcpp' was built under R version 3.6.2
Execution halted
ERROR: lazy loading failed for package 'hal9001'
* removing 'C:/R-3.6.2/library/hal9001'
Error: Failed to install 'hal9001' from GitHub:
  (converted from warning) installation of package ‘C:/Users/Asma/AppData/Local/Temp/Rtmp0efAE9/file27f0d2a570f/hal9001_0.2.5.tar.gz’ had non-zero exit status

**Comment by jeremyrcoyle** [comment]
The line `Error: (converted from warning) package 'Rcpp' was built under R version 3.6.2` would suggest you have a mismatch between your R version and your Rcpp version, which means Rcpp can't load.

**Comment by nhejazi** [comment]
stale

**Comment by Bahamyirou** [comment]
Thank you for the help. IT Works.
