### ISSUE TITLE
Competing work

### ISSUE THREAD

**Issue by daviddewhurst** [tlverse/hal9001#70]
The paper does not talk about competing work at all. If this paper is the first that has been written on software implementation of HAL, this should be clearly stated and then my concern about this will be ameliorated. Otherwise, the authors should more clearly highlight previous implementation of HAL. I see the van der Laan and Dudoit paper series, but it is unclear if these papers are the only prior work, if they address the same questions as this paper, etc.

**Comment by nhejazi** [comment]
Thank you for raising this question. This is indeed the first software implementation of HAL. The series of papers by van der Laan and Dudoit predates HAL significantly; however, we will amend the paper to additionally cite https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5662030/ and the deprecated/unmaintained package https://github.com/benkeser/halplus

**Comment by daviddewhurst** [comment]
Great, this removes any concern I had about this.
