### ISSUE TITLE
Quasibinomial family

### ISSUE THREAD

**Issue by Lauren-EylerDang** [tlverse/hal9001#75]
Hi Nima,

No hurry, but if you could implement family="quasibinomial" as an option in HAL now that cvglmnet allows it, that would be great!

Thanks,
Lauren

**Comment by nhejazi** [comment]
This should be handled after merging of #78 is complete, though the option will be `family = quasibinomial()` (n.b., using the object `stats::quasibinomial()` rather than the character vector).

**Comment by Lauren-EylerDang** [comment]
Awesome, thanks!

**Comment by nhejazi** [comment]
Closing since #78 has been merged into `devel`.
