### ISSUE TITLE
python version

### ISSUE THREAD

**Issue by matthewvowels1** [tlverse/hal9001#89]
Incredibly grateful for you releasing this. 

Is there any plan for a python implementation?

Regards,

**Comment by nhejazi** [comment]
Thanks for your interest in the package. As of now, there are no immediate plans for a Python version of the package, though much of the core procedure (other than the lasso step) is implemented in cpp. At least some of the key aspects of the procedure (e.g., creating the HAL basis / design matrix) can be wrapped around via Python.

Also, I vaguely recall that @benkeser has a student potentially working on a Python version. He may be able to say more on this.

**Comment by benkeser** [comment]
Nothing in the pipeline for python implementation at the moment.

**Comment by matthewvowels1** [comment]
Thanks both for your responses! Understood. In any case, it will be eagerly awaited : ]
